name: Son of Kong Studios
favicon: null
layout_spectrum: 0
typography_spectrum: 0.62032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cfb53e'
    - '#7b6d2c'
    - '#473f1a'
    - '#040404'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
