name: Son of Kong Studios
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe079'
    - '#307b98'
    - '#000000'
    - '#c50013'
    - '#453d1b'
  brandStrength: 1
  lightness: 0.34775729943066835
  saturation: 0.628030925989151
  rhythmicContrast: 0.9290771707892418
purpose: []
