name: Son of Kong Studios
favicon: null
layout_spectrum: 0
typography_spectrum: 0.62032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#e5da2b'
    - '#767016'
    - '#bfbfbf'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
